### ISSUE TITLE
error installing via conda-forge on mac arm64, says "conda.exceptions.UnsatisfiableError" with no info

### ISSUE THREAD

**Issue by grisaitis** [r-lib/pak#480]
for some reason this fails. any tips?

```shell
❯ conda create -v -n myenv -c conda-forge "r-pak"
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                             
Traceback (most recent call last):
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/install.py", line 291, in install
    raise e
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/cli/install.py", line 260, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 319, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/core/solve.py", line 853, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/resolve.py", line 1323, in solve
    self.find_conflicts(specs, specs_to_add, history_specs)
  File "/Users/william/.pyenv/versions/miniforge3/lib/python3.9/site-packages/conda/resolve.py", line 352, in find_conflicts
    raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError
```

my `conda info`:

```shell
❯ conda info

     active environment : base
    active env location : /Users/william/.pyenv/versions/miniforge3
            shell level : 0
       user config file : /Users/william/.condarc
 populated config files : /Users/william/.pyenv/versions/miniforge3/.condarc
                          /Users/william/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.10.final.0
       virtual packages : __osx=11.5.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/william/.pyenv/versions/miniforge3  (writable)
      conda av data dir : /Users/william/.pyenv/versions/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/william/.pyenv/versions/miniforge3/pkgs
                          /Users/william/.conda/pkgs
       envs directories : /Users/william/.pyenv/versions/miniforge3/envs
                          /Users/william/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.10 Darwin/20.6.0 OSX/11.5.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by gaborcsardi** [comment]
This seems like an issue with conda to me, which we cannot do much about, I am afraid.

**Comment by grisaitis** [comment]
in what way?

the same command works for `r-renv` and `r-essentials` (and any other `r-` package i try)

**Comment by gaborcsardi** [comment]
In the way that you are not running any code from the pak package, so I am not sure how we could help you. We also don't create any conda packages, so if there is any issue with r-pak in code, we cannot help with that, either. 

Btw. is it possible that pak is just not packaged in conda?

**Comment by grisaitis** [comment]
ah ok :) thanks for explaining.

somehow, yes, pak is on conda-forge!
- https://anaconda.org/conda-forge/r-pak
- https://github.com/conda-forge/r-pak-feedstock

and it's been downloaded 20k+ times! i assumed it was maintained as part of this project. 

maybe it's automatically generated? eg by some process putting R packages on conda-forge? 

anyway, i understand this is not your issue haha
